kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
spec:
  replicas: 4
  template:
    spec:
      containers:
        - name: whoami
          image: traefik/traefikee-webapp-demo:v2
          args:
            - -ascii
            - -name=FOO
